name: ESLint Review Bot

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  eslint-review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Install node-fetch (required by eslint-review-bot.js)
        run: npm install node-fetch@2

      - name: Run ESLint and Review Bot
        run: |
          npx eslint . --ext .js,.jsx,.ts,.tsx --max-warnings=0
          npx eslint . -f json -o eslint-report.json
