name: ESLint Review Bot

on:
  pull_request:
    types: [opened, synchronize]

permissions:
  pull-requests: write
  contents: read

jobs:
  eslint-review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch full history

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Install node-fetch (required by eslint-review-bot.js)
        run: npm install node-fetch@2

      - name: Get changed files
        id: changed-files
        run: |
          echo "::group::Detecting changed files"
          git fetch origin ${{ github.base_ref }}
          git diff --name-only origin/${{ github.base_ref }}...HEAD -- '*.js' '*.jsx' '*.ts' '*.tsx' > changed-files.txt
          cat changed-files.txt
          echo "::endgroup::"

      - name: Run ESLint on changed files
        if: success()
        run: |
          CHANGED_FILES=$(cat changed-files.txt | xargs)
          if [ -z "$CHANGED_FILES" ]; then
            echo "No JS/TS files changed. Skipping ESLint."
            exit 0
          fi
          npx eslint $CHANGED_FILES -f json -o eslint-report.json

      - name: Post or update ESLint comment on PR
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
        run: node .github/scripts/eslint-review-bot.js
